"""Canonical Asset Profile domain exports."""

from vscs.domain.caps.asset_generation import (
    CanonicalAssetGenerationRequest,
    GeneratedCanonicalAsset,
)
from vscs.domain.caps.generation import (
    CanonicalFactExtraction,
    CAPCanonAnalysis,
    CAPGenerationRequest,
    CAPSectionConfidence,
    ExtractedCanonicalFact,
    GeneratedCAPDraft,
)
from vscs.domain.caps.models import CanonicalAssetProfile, CAPCreate, CAPStatus, CAPUpdate
from vscs.domain.caps.production_contract import (
    CanonicalConstraint,
    CanonicalConstraintKind,
    CanonicalFact,
    CanonicalIdentity,
    CanonicalProductionContract,
    CanonicalReferenceFamily,
    CanonicalReferenceLifecycle,
    CanonicalReferenceOrigin,
    CanonicalReferenceView,
    CAPReadiness,
    CAPReadinessState,
    FunctionalCapability,
    ProductionAssetProjection,
    ProductionReference,
)
from vscs.domain.caps.production_projection import (
    ProductionProjection,
    ProductionProjectionResult,
)
from vscs.domain.caps.readiness import (
    ReadinessAssessment,
    ReadinessDimension,
    ReadinessGap,
    ReadinessReport,
    ReadinessResult,
    ReadinessSeverity,
    ReadinessState,
)
from vscs.domain.caps.reference_library import (
    ReferenceLibraryEntry,
    ReferenceLibrarySnapshot,
    ReferenceLifecycleAction,
    ReferenceLifecycleEvent,
)
from vscs.domain.caps.reference_templates import (
    CategoryReferenceTemplate,
    CategoryReferenceTemplateRegistry,
    ReferenceCoverage,
    ReferenceRequirement,
    default_category_reference_templates,
)
from vscs.domain.caps.references import (
    CanonicalReference,
    CanonicalReferenceCreate,
    CanonicalReferenceRole,
    CanonicalReferenceStatus,
    CanonicalReferenceType,
    CanonicalReferenceUpdate,
)
from vscs.domain.caps.structured_knowledge import (
    KnowledgeAuthority,
    PersistedCanonicalConstraint,
    PersistedCanonicalFact,
    PersistedFunctionalCapability,
    StructuredCAPKnowledge,
    is_production_authority,
)

__all__ = (
    "CAPCanonAnalysis",
    "CAPCreate",
    "CAPGenerationRequest",
    "CAPReadiness",
    "CAPReadinessState",
    "CAPSectionConfidence",
    "CAPStatus",
    "CAPUpdate",
    "CanonicalAssetGenerationRequest",
    "CanonicalAssetProfile",
    "CanonicalConstraint",
    "CanonicalConstraintKind",
    "CanonicalFact",
    "CanonicalFactExtraction",
    "CanonicalIdentity",
    "CanonicalProductionContract",
    "CanonicalReference",
    "CanonicalReferenceCreate",
    "CanonicalReferenceFamily",
    "CanonicalReferenceLifecycle",
    "CanonicalReferenceOrigin",
    "CanonicalReferenceRole",
    "CanonicalReferenceStatus",
    "CanonicalReferenceType",
    "CanonicalReferenceUpdate",
    "CanonicalReferenceView",
    "CategoryReferenceTemplate",
    "CategoryReferenceTemplateRegistry",
    "ExtractedCanonicalFact",
    "FunctionalCapability",
    "GeneratedCAPDraft",
    "GeneratedCanonicalAsset",
    "KnowledgeAuthority",
    "PersistedCanonicalConstraint",
    "PersistedCanonicalFact",
    "PersistedFunctionalCapability",
    "ProductionAssetProjection",
    "ProductionProjection",
    "ProductionProjectionResult",
    "ProductionReference",
    "ReadinessAssessment",
    "ReadinessDimension",
    "ReadinessGap",
    "ReadinessReport",
    "ReadinessResult",
    "ReadinessSeverity",
    "ReadinessState",
    "ReferenceCoverage",
    "ReferenceLibraryEntry",
    "ReferenceLibrarySnapshot",
    "ReferenceLifecycleAction",
    "ReferenceLifecycleEvent",
    "ReferenceRequirement",
    "StructuredCAPKnowledge",
    "default_category_reference_templates",
    "is_production_authority",
)
