"""Advanced Clip Production Package public API."""

from .builder import ACPPBuildError, ClipProductionPackageBuilder
from .bundle import (
    BundleValidationIssue,
    BundleValidationResult,
    BundleValidationSeverity,
    ProductionBundle,
    ProductionBundleSerializer,
    ProductionBundleValidationError,
    ProductionBundleValidator,
)
from .catalogs import CAPAssetResolutionCatalog, FilesystemBehaviourResolutionCatalog
from .compiler import ACPPCompilationError, ACPPCompilerConfig, SSIEToACPPCompiler
from .identifiers import build_clip_id
from .models import (
    AssetBinding,
    AssetBindingRole,
    AudioSpecification,
    ClipIdentity,
    ClipProductionPackage,
    ContinuityBinding,
    OutputSpecification,
    PromptSpecification,
    RenderQualityMode,
    RenderSpecification,
    SeedPolicy,
)
from .prompt_compiler import (
    ACPPPromptCompiler,
    CompiledProductionPrompt,
    CompiledPromptSection,
    PromptCompilationError,
    PromptCompilerConfig,
    PromptContribution,
    PromptContributionCatalog,
)
from .protocols import ClipPackageSerializer, ClipPackageValidator
from .reference_roles import (
    CropRisk,
    ProviderReadyReferenceResolver,
    ProviderReferenceBinding,
    ProviderReferenceCapabilities,
    ReferenceCatalog,
    ReferenceClass,
    ReferenceCoverage,
    ReferencePlan,
    ReferencePriority,
    ReferenceResolutionDiagnostic,
    ReferenceResolutionResult,
    ReferenceResolutionSeverity,
    ReferenceRole,
    ReferenceRoleRequest,
    ReferenceSubjectType,
    ReferenceTarget,
    ShotReference,
)
from .render_jobs import (
    RenderCapability,
    RenderInputReference,
    RenderJob,
    RenderJobCompilationError,
    RenderJobCompiler,
    RenderJobCompilerConfig,
    RetryPolicy,
)
from .resolution import (
    ACPPResolutionResult,
    ACPPResolverConfig,
    AssetResolutionCatalog,
    AssetResolutionRecord,
    BehaviourResolutionCatalog,
    BehaviourResolutionRecord,
    CanonicalReferenceResolution,
    ResolutionDiagnostic,
    ResolutionProvenance,
    ResolutionSeverity,
)
from .resolver import ACPPResolutionError, ACPPResourceResolver
from .serialization import ACPPSerializationError, ACPPSerializer
from .service import ACPPEditorError, ACPPEditorService
from .validator import (
    ACPPValidationIssue,
    ACPPValidationResult,
    ACPPValidationSeverity,
    ACPPValidator,
)

__all__ = [
    "ACPPBuildError",
    "ACPPCompilationError",
    "ACPPCompilerConfig",
    "ACPPEditorError",
    "ACPPEditorService",
    "ACPPPromptCompiler",
    "ACPPResolutionError",
    "ACPPResolutionResult",
    "ACPPResolverConfig",
    "ACPPResourceResolver",
    "ACPPSerializationError",
    "ACPPSerializer",
    "ACPPValidationIssue",
    "ACPPValidationResult",
    "ACPPValidationSeverity",
    "ACPPValidator",
    "AssetBinding",
    "AssetBindingRole",
    "AssetResolutionCatalog",
    "AssetResolutionRecord",
    "AudioSpecification",
    "BehaviourResolutionCatalog",
    "BehaviourResolutionRecord",
    "BundleValidationIssue",
    "BundleValidationResult",
    "BundleValidationSeverity",
    "CAPAssetResolutionCatalog",
    "CanonicalReferenceResolution",
    "ClipIdentity",
    "ClipPackageSerializer",
    "ClipPackageValidator",
    "ClipProductionPackage",
    "ClipProductionPackageBuilder",
    "CompiledProductionPrompt",
    "CompiledPromptSection",
    "ContinuityBinding",
    "CropRisk",
    "FilesystemBehaviourResolutionCatalog",
    "OutputSpecification",
    "ProductionBundle",
    "ProductionBundleSerializer",
    "ProductionBundleValidationError",
    "ProductionBundleValidator",
    "PromptCompilationError",
    "PromptCompilerConfig",
    "PromptContribution",
    "PromptContributionCatalog",
    "PromptSpecification",
    "ProviderReadyReferenceResolver",
    "ProviderReferenceBinding",
    "ProviderReferenceCapabilities",
    "ReferenceCatalog",
    "ReferenceClass",
    "ReferenceCoverage",
    "ReferencePlan",
    "ReferencePriority",
    "ReferenceResolutionDiagnostic",
    "ReferenceResolutionResult",
    "ReferenceResolutionSeverity",
    "ReferenceRole",
    "ReferenceRoleRequest",
    "ReferenceSubjectType",
    "ReferenceTarget",
    "RenderCapability",
    "RenderInputReference",
    "RenderJob",
    "RenderJobCompilationError",
    "RenderJobCompiler",
    "RenderJobCompilerConfig",
    "RenderQualityMode",
    "RenderSpecification",
    "ResolutionDiagnostic",
    "ResolutionProvenance",
    "ResolutionSeverity",
    "RetryPolicy",
    "SSIEToACPPCompiler",
    "SeedPolicy",
    "ShotReference",
    "build_clip_id",
]
