"""VSCS vNext ProductionTask domain, compilation and governance public API."""

from .compatibility import PRODUCTION_TASK_ID_METADATA_KEY, ProductionTaskLegacyBridge
from .compiler import (
    ProductionTaskCompilationContext,
    ProductionTaskCompilationError,
    ProductionTaskCompilerService,
)
from .governance import (
    ProductionTaskGovernanceError,
    ProductionTaskGovernanceIssue,
    ProductionTaskGovernanceResult,
    ProductionTaskGovernanceService,
    ProductionTaskGovernanceSeverity,
)
from .graph import (
    ProductionTaskDependencyDisposition,
    ProductionTaskGraph,
    ProductionTaskGraphError,
    ProductionTaskGraphIntegrationService,
    ProductionTaskGraphRefreshResult,
)
from .lifecycle import (
    ProductionTaskLifecycleService,
    ProductionTaskStageService,
    ProductionTaskTransition,
    ProductionTaskTransitionError,
)
from .models import (
    ProductionAuthorityType,
    ProductionCapability,
    ProductionTask,
    ProductionTaskAttemptPolicy,
    ProductionTaskAuthority,
    ProductionTaskPriority,
    ProductionTaskState,
    ProductionTaskType,
)
from .production_queue import (
    ProductionQueue,
    ProductionQueueAttempt,
    ProductionQueueCompilerService,
    ProductionQueueEngine,
    ProductionQueueEntry,
    ProductionQueueError,
    ProductionQueueState,
)
from .repository import ProductionTaskRepository, ProductionTaskRepositoryError
from .resources import (
    ProductionResource,
    ProductionResourceCatalog,
    ProductionResourceCatalogError,
    ProductionResourceMatch,
    ProductionResourceState,
)
from .schedule_records import (
    ProductionSchedulePersistenceError,
    ProductionSchedulePersistenceService,
    ProductionScheduleRepository,
    ProductionScheduleReviewDecision,
    ProductionScheduleReviewError,
    ProductionScheduleReviewRecord,
    ProductionScheduleReviewService,
    ProductionScheduleReviewState,
    ProductionScheduleReviewView,
    ProductionScheduleSnapshot,
    production_schedule_fingerprint,
)
from .scheduler import (
    ProductionSchedule,
    ProductionScheduleAssignment,
    ProductionScheduleDeferral,
    ProductionScheduler,
    ProductionSchedulingDeferralReason,
    ProductionSchedulingError,
    ProductionSchedulingService,
)
from .service import ProductionTaskApplicationService

__all__ = [
    "PRODUCTION_TASK_ID_METADATA_KEY",
    "ProductionAuthorityType",
    "ProductionCapability",
    "ProductionQueue",
    "ProductionQueueAttempt",
    "ProductionQueueCompilerService",
    "ProductionQueueEngine",
    "ProductionQueueEntry",
    "ProductionQueueError",
    "ProductionQueueState",
    "ProductionResource",
    "ProductionResourceCatalog",
    "ProductionResourceCatalogError",
    "ProductionResourceMatch",
    "ProductionResourceState",
    "ProductionSchedule",
    "ProductionScheduleAssignment",
    "ProductionScheduleDeferral",
    "ProductionSchedulePersistenceError",
    "ProductionSchedulePersistenceService",
    "ProductionScheduleRepository",
    "ProductionScheduleReviewDecision",
    "ProductionScheduleReviewError",
    "ProductionScheduleReviewRecord",
    "ProductionScheduleReviewService",
    "ProductionScheduleReviewState",
    "ProductionScheduleReviewView",
    "ProductionScheduleSnapshot",
    "ProductionScheduler",
    "ProductionSchedulingDeferralReason",
    "ProductionSchedulingError",
    "ProductionSchedulingService",
    "ProductionTask",
    "ProductionTaskApplicationService",
    "ProductionTaskAttemptPolicy",
    "ProductionTaskAuthority",
    "ProductionTaskCompilationContext",
    "ProductionTaskCompilationError",
    "ProductionTaskCompilerService",
    "ProductionTaskDependencyDisposition",
    "ProductionTaskGovernanceError",
    "ProductionTaskGovernanceIssue",
    "ProductionTaskGovernanceResult",
    "ProductionTaskGovernanceService",
    "ProductionTaskGovernanceSeverity",
    "ProductionTaskGraph",
    "ProductionTaskGraphError",
    "ProductionTaskGraphIntegrationService",
    "ProductionTaskGraphRefreshResult",
    "ProductionTaskLegacyBridge",
    "ProductionTaskLifecycleService",
    "ProductionTaskPriority",
    "ProductionTaskRepository",
    "ProductionTaskRepositoryError",
    "ProductionTaskStageService",
    "ProductionTaskState",
    "ProductionTaskTransition",
    "ProductionTaskTransitionError",
    "ProductionTaskType",
    "production_schedule_fingerprint",
]
