"""VSCS vNext ProductionTask domain, compilation and governance public API."""

from .compatibility import PRODUCTION_TASK_ID_METADATA_KEY, ProductionTaskLegacyBridge
from .compiler import (
    ProductionTaskCompilationContext,
    ProductionTaskCompilationError,
    ProductionTaskCompilerService,
)
from .governance import (
    ProductionTaskGovernanceError,
    ProductionTaskGovernanceIssue,
    ProductionTaskGovernanceResult,
    ProductionTaskGovernanceService,
    ProductionTaskGovernanceSeverity,
)
from .graph import (
    ProductionTaskDependencyDisposition,
    ProductionTaskGraph,
    ProductionTaskGraphError,
    ProductionTaskGraphIntegrationService,
    ProductionTaskGraphRefreshResult,
)
from .lifecycle import (
    ProductionTaskLifecycleService,
    ProductionTaskStageService,
    ProductionTaskTransition,
    ProductionTaskTransitionError,
)
from .models import (
    ProductionAuthorityType,
    ProductionCapability,
    ProductionTask,
    ProductionTaskAttemptPolicy,
    ProductionTaskAuthority,
    ProductionTaskPriority,
    ProductionTaskState,
    ProductionTaskType,
)
from .production_queue import (
    ProductionQueue,
    ProductionQueueAttempt,
    ProductionQueueCompilerService,
    ProductionQueueEngine,
    ProductionQueueEntry,
    ProductionQueueError,
    ProductionQueueState,
)
from .production_readiness import (
    ProductionReadinessAssessment,
    ProductionReadinessCode,
    ProductionReadinessFinding,
    ProductionReadinessIntegrationService,
    ProductionReadinessSeverity,
    ProductionReadinessStatus,
)
from .repository import ProductionTaskRepository, ProductionTaskRepositoryError
from .resources import (
    ProductionResource,
    ProductionResourceCatalog,
    ProductionResourceCatalogError,
    ProductionResourceMatch,
    ProductionResourceState,
)
from .runtime import (
    ProductionExecutionLease,
    ProductionLeaseManager,
    ProductionQueueClaim,
    ProductionQueueRuntimeService,
    ProductionWorker,
    ProductionWorkerError,
    ProductionWorkerRegistry,
    ProductionWorkerState,
)
from .schedule_records import (
    ProductionSchedulePersistenceError,
    ProductionSchedulePersistenceService,
    ProductionScheduleRepository,
    ProductionScheduleReviewDecision,
    ProductionScheduleReviewError,
    ProductionScheduleReviewRecord,
    ProductionScheduleReviewService,
    ProductionScheduleReviewState,
    ProductionScheduleReviewView,
    ProductionScheduleSnapshot,
    production_schedule_fingerprint,
)
from .scheduler import (
    ProductionSchedule,
    ProductionScheduleAssignment,
    ProductionScheduleDeferral,
    ProductionScheduler,
    ProductionSchedulingDeferralReason,
    ProductionSchedulingError,
    ProductionSchedulingService,
)
from .scheduling_monitoring import (
    ProductionQueueProgressSnapshot,
    ProductionSchedulingMonitor,
    ProductionSchedulingMonitoringConfig,
    ProductionSchedulingMonitoringSnapshot,
    ProductionSchedulingRecoveryResult,
    ProductionSchedulingRecoveryService,
    ProductionWorkerRuntimeSnapshot,
    SchedulingMonitoringDiagnostic,
    SchedulingMonitoringSeverity,
    SchedulingRecoveryAction,
    SchedulingRecoveryDecision,
    SchedulingRecoveryEvent,
    SchedulingRecoveryReason,
)
from .service import ProductionTaskApplicationService
from .ui_service import ProductionSchedulingUiError, ProductionSchedulingUiService

__all__ = [
    "PRODUCTION_TASK_ID_METADATA_KEY",
    "ProductionAuthorityType",
    "ProductionCapability",
    "ProductionExecutionLease",
    "ProductionLeaseManager",
    "ProductionQueue",
    "ProductionQueueAttempt",
    "ProductionQueueClaim",
    "ProductionQueueCompilerService",
    "ProductionQueueEngine",
    "ProductionQueueEntry",
    "ProductionQueueError",
    "ProductionQueueProgressSnapshot",
    "ProductionQueueRuntimeService",
    "ProductionQueueState",
    "ProductionReadinessAssessment",
    "ProductionReadinessCode",
    "ProductionReadinessFinding",
    "ProductionReadinessIntegrationService",
    "ProductionReadinessSeverity",
    "ProductionReadinessStatus",
    "ProductionResource",
    "ProductionResourceCatalog",
    "ProductionResourceCatalogError",
    "ProductionResourceMatch",
    "ProductionResourceState",
    "ProductionSchedule",
    "ProductionScheduleAssignment",
    "ProductionScheduleDeferral",
    "ProductionSchedulePersistenceError",
    "ProductionSchedulePersistenceService",
    "ProductionScheduleRepository",
    "ProductionScheduleReviewDecision",
    "ProductionScheduleReviewError",
    "ProductionScheduleReviewRecord",
    "ProductionScheduleReviewService",
    "ProductionScheduleReviewState",
    "ProductionScheduleReviewView",
    "ProductionScheduleSnapshot",
    "ProductionScheduler",
    "ProductionSchedulingDeferralReason",
    "ProductionSchedulingError",
    "ProductionSchedulingMonitor",
    "ProductionSchedulingMonitoringConfig",
    "ProductionSchedulingMonitoringSnapshot",
    "ProductionSchedulingRecoveryResult",
    "ProductionSchedulingRecoveryService",
    "ProductionSchedulingService",
    "ProductionSchedulingUiError",
    "ProductionSchedulingUiService",
    "ProductionTask",
    "ProductionTaskApplicationService",
    "ProductionTaskAttemptPolicy",
    "ProductionTaskAuthority",
    "ProductionTaskCompilationContext",
    "ProductionTaskCompilationError",
    "ProductionTaskCompilerService",
    "ProductionTaskDependencyDisposition",
    "ProductionTaskGovernanceError",
    "ProductionTaskGovernanceIssue",
    "ProductionTaskGovernanceResult",
    "ProductionTaskGovernanceService",
    "ProductionTaskGovernanceSeverity",
    "ProductionTaskGraph",
    "ProductionTaskGraphError",
    "ProductionTaskGraphIntegrationService",
    "ProductionTaskGraphRefreshResult",
    "ProductionTaskLegacyBridge",
    "ProductionTaskLifecycleService",
    "ProductionTaskPriority",
    "ProductionTaskRepository",
    "ProductionTaskRepositoryError",
    "ProductionTaskStageService",
    "ProductionTaskState",
    "ProductionTaskTransition",
    "ProductionTaskTransitionError",
    "ProductionTaskType",
    "ProductionWorker",
    "ProductionWorkerError",
    "ProductionWorkerRegistry",
    "ProductionWorkerRuntimeSnapshot",
    "ProductionWorkerState",
    "SchedulingMonitoringDiagnostic",
    "SchedulingMonitoringSeverity",
    "SchedulingRecoveryAction",
    "SchedulingRecoveryDecision",
    "SchedulingRecoveryEvent",
    "SchedulingRecoveryReason",
    "production_schedule_fingerprint",
]
