"""Structured story application services."""

from .approval import (
    StoryApprovalAction,
    StoryApprovalError,
    StoryApprovalRecord,
    StoryApprovalService,
    StoryApprovalSnapshot,
)
from .asset_resolver import (
    AssetBindingStatus,
    GovernedAssetResolutionError,
    GovernedAssetResolutionService,
    ShotAssetBinding,
)
from .bootstrap import (
    register_episode_planning,
    register_governed_asset_resolution,
    register_governed_camera_planning,
    register_governed_lighting_planning,
    register_governed_shot_planning,
    register_scene_planning,
    register_story_approval,
    register_story_lifecycle,
    register_story_metadata,
    register_story_status,
)
from .camera_planning import (
    CameraAngle,
    CameraMovement,
    CameraPlan,
    CameraPlanStatus,
    GovernedCameraPlanningError,
    GovernedCameraPlanningService,
    LensFamily,
    ScreenDirection,
    ShotSize,
)
from .containers import (
    ProductionContainerType,
    build_scene_id,
    infer_container_type,
    normalize_container_id,
)
from .episode_planning import (
    EpisodePlan,
    EpisodePlanningError,
    EpisodePlanningService,
    EpisodePlanStatus,
)
from .hierarchy import (
    StoryHierarchy,
    StoryItemStatus,
    StoryNode,
    StoryNodeKind,
    StoryStatistics,
    build_story_hierarchy,
    scene_status,
)
from .iterative_scene_planning import IterativeScenePlanningService
from .lifecycle import (
    StoryLifecycleError,
    StoryLifecycleService,
    StoryRecord,
    StorySourceType,
    StoryStatus,
)
from .lighting_planning import (
    ExposureIntent,
    GovernedLightingPlanningError,
    GovernedLightingPlanningService,
    KeyDirection,
    LightingIntent,
    LightingPlan,
    LightingPlanStatus,
    LightQuality,
)
from .metadata import (
    StoryMetadata,
    StoryMetadataCompleteness,
    StoryMetadataError,
    StoryMetadataService,
)
from .scene_planning import ScenePlan, ScenePlanningError, ScenePlanStatus
from .service import StoryService, StoryServiceError
from .shot_planning import (
    GovernedShotPlanningError,
    GovernedShotPlanningService,
    ShotPlan,
    ShotPlanStatus,
)
from .status import (
    StoryStatusError,
    StoryStatusService,
    StoryStatusSnapshot,
    StoryStatusTransition,
)

ScenePlanningService = IterativeScenePlanningService

__all__ = [
    "AssetBindingStatus",
    "CameraAngle",
    "CameraMovement",
    "CameraPlan",
    "CameraPlanStatus",
    "EpisodePlan",
    "EpisodePlanStatus",
    "EpisodePlanningError",
    "EpisodePlanningService",
    "ExposureIntent",
    "GovernedAssetResolutionError",
    "GovernedAssetResolutionService",
    "GovernedCameraPlanningError",
    "GovernedCameraPlanningService",
    "GovernedLightingPlanningError",
    "GovernedLightingPlanningService",
    "GovernedShotPlanningError",
    "GovernedShotPlanningService",
    "IterativeScenePlanningService",
    "KeyDirection",
    "LensFamily",
    "LightingIntent",
    "LightingPlan",
    "LightingPlanStatus",
    "LightQuality",
    "ProductionContainerType",
    "ScenePlan",
    "ScenePlanStatus",
    "ScenePlanningError",
    "ScenePlanningService",
    "ScreenDirection",
    "ShotAssetBinding",
    "ShotPlan",
    "ShotPlanStatus",
    "ShotSize",
    "StoryApprovalAction",
    "StoryApprovalError",
    "StoryApprovalRecord",
    "StoryApprovalService",
    "StoryApprovalSnapshot",
    "StoryHierarchy",
    "StoryItemStatus",
    "StoryLifecycleError",
    "StoryLifecycleService",
    "StoryMetadata",
    "StoryMetadataCompleteness",
    "StoryMetadataError",
    "StoryMetadataService",
    "StoryNode",
    "StoryNodeKind",
    "StoryRecord",
    "StoryService",
    "StoryServiceError",
    "StorySourceType",
    "StoryStatistics",
    "StoryStatus",
    "StoryStatusError",
    "StoryStatusService",
    "StoryStatusSnapshot",
    "StoryStatusTransition",
    "build_scene_id",
    "build_story_hierarchy",
    "infer_container_type",
    "normalize_container_id",
    "register_episode_planning",
    "register_governed_asset_resolution",
    "register_governed_camera_planning",
    "register_governed_lighting_planning",
    "register_governed_shot_planning",
    "register_scene_planning",
    "register_story_approval",
    "register_story_lifecycle",
    "register_story_metadata",
    "register_story_status",
    "scene_status",
]
